### ISSUE TITLE
Dictionary crack does not work

### ISSUE THREAD

**Issue by torabi12** [saurabhwadekar/pycrack#1]
May I do something wrongly, but I get this:
![kép](https://user-images.githubusercontent.com/98665813/216785213-98def7d7-4663-4024-8b01-cd0ea10a033c.png)

I put the install.zip and rockyou.txt to the folder of PyCrack.
Could you help what is wrong?

**Comment by saurabhwadekar** [comment]
Would you mind sending me the rockyou.txt  file so I can figure it out?

**Comment by torabi12** [comment]
I used the classic one from here:
https://github.com/praetorian-inc/Hob0Rules/blob/master/wordlists/rockyou.txt.gz

I extracted it and copied to the PyCrack folder. The install.zip was also in the same place in pycrack.
Thank you!

**Comment by saurabhwadekar** [comment]
Please reinstall and it will work.
The bug has been completely fixed.

and thanks for your feedback ❤️

**Comment by torabi12** [comment]
Yes it works fine:
![kép](https://user-images.githubusercontent.com/98665813/216820401-82b97797-204e-4983-ac31-1ae526479fff.png)

Thank you the quick fix:)

**Comment by torabi12** [comment]
Dear Saurabh,

I would like to ask one more question.
I created a ZIP file with AES-256 encription, the password is:

50=1r%9ZhFW\Zrf`O9k?`eEBaPFiTf5.

The file includes one txt file, which contains the password:)

This password does not available in rockyou.txt and the scan starts but after a while I get this error and the tool gives back the prompt:

![kép](https://user-images.githubusercontent.com/98665813/216838001-b96ebb7f-b038-4b18-ae44-c3fb28e7b6c6.png)

I also attached my test file:
[install.zip](https://github.com/saurabhwadekar/pycrack/files/10611849/install.zip)

Could you please check this or similar scenario if it is working for you?

Github formats the pasword above after O9k? there is a ´ sign and comes the small e

Thank you very much!

Regards,
Arpad/torabi12

**Comment by saurabhwadekar** [comment]
I also got this error but I fixed it after some time. you should clone the repo and install it again

**Comment by torabi12** [comment]
I reinstalled today the app and I tried dictionary mode for a ZIP file.
The ZIP password is: c4wTja7SxxQHO6IFfweE

This was the beginning:
![kép](https://user-images.githubusercontent.com/98665813/217621205-c908aef8-0532-43b1-95d4-264d7106aec4.png)

and at the end:
![kép](https://user-images.githubusercontent.com/98665813/217621255-eadb4bf8-84e7-43eb-8006-9aacea3a4a6d.png)

I used this ZIP file:
[flag.zip](https://github.com/saurabhwadekar/pycrack/files/10688816/flag.zip)

I think the output should contain only the valuable information.
