### ISSUE TITLE
Can't install it. What am I doing wrong?

### ISSUE THREAD

**Issue by thebendsbaby** [saurabhwadekar/pycrack#2]
![Screenshot from 2023-04-26 21-20-33](https://user-images.githubusercontent.com/131928367/234729982-5311605c-34af-4e99-9d1f-f26795a976ae.png)
Thanks

**Comment by saurabhwadekar** [comment]
Install pip in your system.

1) sudo apt update
2) sudo apt install python3-pip
3) ./install.sh

**Comment by thebendsbaby** [comment]
Thanks

**Comment by saurabhwadekar** [comment]
Please close it if your issue is resolved
